---
title: "PlayerPlots_3Pos"
author: "Greg"
date: "2024-01-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/gregorylederer/Desktop/UMass Basketball")
```

#packages
```{r}
library(cbbplotR)
library(cbbdata)
cbbdata::cbd_login(username = 'glederer', password = 'Bryce.0819')
library(tidyverse)
library(dplyr)
library(glue)
library(tidyr)
```

#inputs
```{r}
Team <- 'La Salle'
savename1 <- paste0(Team, ' | Guard Plot 1.png')
savename2 <- paste0(Team, ' | Guard Plot 2.png')
savename3 <- paste0(Team, ' | Wing Plot 1.png')
savename4 <- paste0(Team, ' | Wing Plot 2.png')
savename5 <- paste0(Team, ' | Big Plot 1.png')
savename6 <- paste0(Team, ' | Big Plot 2.png')
```

#data
```{r}
data <- cbd_torvik_player_season(year = 2024) %>% filter(team %in% c('Massachusetts', Team)) %>% filter(min > 15) %>%
  mutate(
    pos_group = case_when(pos %in% c('Combo G', 'Pure PG', 'Scoring PG') ~ 'Guard',
                          pos %in% c('Wing F', 'Wing G', 'Stretch 4') ~ 'Wing',
                          pos %in% c('C', 'PF/C') ~ 'Big')
  )

Guards <- data %>% filter(pos_group == 'Guard')
Wings <- data %>% filter(pos_group == 'Wing')
Bigs <- data %>% filter(pos_group == 'Big')
```

#guard plot
adj o/d
ast/to, efg
```{r}
player_ids1 <- get_espn_players('UMass') %>% rename(player = displayName)
player_ids2 <- get_espn_players(Team) %>% rename(player = displayName)
player_ids <- rbind(player_ids1, player_ids2)
Guards <- Guards %>%
  left_join(player_ids, by = 'player') %>%
  separate(player, into = c('first_name', 'last_name'), sep = ' ')

guard_plot1 <- Guards %>%
  ggplot(aes(adj_oe, adj_de)) +
  geom_mean_lines(aes(x0 = adj_oe, y0 = adj_de), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('Adjusted Efficiencies | Guards'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Offense',
       y = 'Defense') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold')
  )
guard_plot1

guard_plot2 <- Guards %>%
  ggplot(aes(ast_to, efg)) +
  geom_mean_lines(aes(x0 = ast_to, y0 = efg), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('Ast/Tov vs. eFG% | Guards'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Ast/Tov',
       y = 'eFG%') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold')
  )
guard_plot2
```

#wings
adj o/d
PPS & usg
```{r}
Wings <- Wings %>%
  left_join(player_ids, by = 'player') %>%
  separate(player, into = c('first_name', 'last_name'), sep = ' ') %>%
  mutate(
    Pts = (ppg * g)
  ) %>%
  mutate(
    PPS = Pts / fga
  )

wing_plot1 <- Wings %>%
  ggplot(aes(adj_oe, adj_de)) +
  geom_mean_lines(aes(x0 = adj_oe, y0 = adj_de), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('Adjusted Efficiencies | Wings'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Offense',
       y = 'Defense') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold')
  )
wing_plot1

wing_plot2 <- Wings %>%
  ggplot(aes(PPS, usg)) +
  geom_mean_lines(aes(x0 = PPS, y0 = usg), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('PPS vs. usg% | Wings'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Points per Shot',
       y = 'usg%') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold')
  )
wing_plot2
```

#bigs
adj o/d
fg%, ORB rate
```{r}
Bigs <- Bigs %>%
  left_join(player_ids, by = 'player') %>%
  separate(player, into = c('first_name', 'last_name'), sep = ' ') %>%
  mutate(
    fg_pct = round(fg_pct*100,1)
  )

big_plot1 <- Bigs %>%
  ggplot(aes(adj_oe, adj_de)) +
  geom_mean_lines(aes(x0 = adj_oe, y0 = adj_de), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('Adjusted Efficiencies | Bigs'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Offense',
       y = 'Defense') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold')
  )
big_plot1

big_plot2 <- Bigs %>%
  ggplot(aes(oreb_rate, fg_pct)) +
  geom_mean_lines(aes(x0 = oreb_rate, y0 = fg_pct), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('ORB% vs. FG% | Bigs'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'ORB%',
       y = 'FG%') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold')
  )
big_plot2
```


```{r}
ggsave(plot = guard_plot1, filename = savename1)
ggsave(plot = guard_plot2, filename = savename2)
ggsave(plot = wing_plot1, filename = savename3)
ggsave(plot = wing_plot2, filename = savename4)
ggsave(plot = big_plot1, filename = savename5)
ggsave(plot = big_plot2, filename = savename6)
```

