---
title: "PlayerPlots_2Pos"
author: "Greg"
date: "2024-01-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/gregorylederer/Desktop/UMass Basketball")
```

#packages
```{r}
library(cbbplotR)
library(cbbdata)
cbbdata::cbd_login(username = 'glederer', password = 'Bryce.0819')
library(tidyverse)
library(dplyr)
library(glue)
library(tidyr)
```

#inputs
```{r}
Team <- 'La Salle'

savename1 <- paste0(Team, ' | Guard Plot 1.png')
savename2 <- paste0(Team, ' | Guard Plot 2.png')
savename3 <- paste0(Team, ' | Guard Plot 3.png')
savename4 <- paste0(Team, ' | Big Plot 1.png')
savename5 <- paste0(Team, ' | Big Plot 2.png')
savename6 <- paste0(Team, ' | Big Plot 3.png')
```

#data
```{r}
data <- cbd_torvik_player_season(year = 2024) %>% filter(team %in% c('Massachusetts', Team)) %>% filter(min > 20) %>%
  mutate(
    pos_group = case_when(pos %in% c('Combo G', 'Pure PG', 'Scoring PG', 'Wing G') ~ 'Guard',
                          pos %in% c('Wing F', 'Stretch 4', 'C', 'PF/C') ~ 'Big')
  )

Guard <- data %>% filter(pos_group == 'Guard')
Big <- data %>% filter(pos_group == 'Big')
```

#Guard plots
adj o/d
efg ast/to
pts usg
```{r}
player_ids1 <- get_espn_players('UMass') %>% rename(player = displayName)
player_ids2 <- get_espn_players(Team) %>% rename(player = displayName)
player_ids <- rbind(player_ids1, player_ids2)
Guard <- Guard %>%
  left_join(player_ids, by = 'player') %>%
  separate(player, into = c('first_name', 'last_name'), sep = ' ')
xmin <- min(Guard$adj_oe) - 2.5
xmax <- max(Guard$adj_oe) + 2.5
ymin <- min(Guard$adj_de) - 2.5
ymax <- max(Guard$adj_de) + 2.5

guard_plot1 <- Guard %>%
  ggplot(aes(adj_oe, adj_de)) +
  geom_mean_lines(aes(x0 = adj_oe, y0 = adj_de), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('Adjusted Efficiencies | Guards'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Offense',
       y = 'Defense') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold'),
    panel.grid.major = element_line(size = 1, color = 'white'),
    panel.grid.minor = element_line(size = 0.5, color = 'white')
  ) +
  lims(x = c(xmin, xmax), y = c(ymin, ymax))
guard_plot1

xmin <- min(Guard$ast_to) - 0.125
xmax <- max(Guard$ast_to) + 0.125
ymin <- min(Guard$efg) - 2.5
ymax <- max(Guard$efg) + 2.5

guard_plot2 <- Guard %>%
  ggplot(aes(ast_to, efg)) +
  geom_mean_lines(aes(x0 = ast_to, y0 = efg), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('Ast/Tov vs. eFG% | Guards'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Ast/Tov',
       y = 'eFG%') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold'),
    panel.grid.major = element_line(size = 1, color = 'white'),
    panel.grid.minor = element_line(size = 0.5, color = 'white')
  ) +
  lims(x = c(xmin, xmax), y = c(ymin, ymax))
guard_plot2

xmin <- min(Guard$ppg) - 1
xmax <- max(Guard$ppg) + 1
ymin <- min(Guard$usg) - 1.25
ymax <- max(Guard$usg) + 1.25

guard_plot3 <- Guard %>%
  ggplot(aes(ppg, usg)) +
  geom_mean_lines(aes(x0 = ppg, y0 = usg), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('Points vs. USG% | Guards'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Points',
       y = 'USG%') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold'),
    panel.grid.major = element_line(size = 1, color = 'white'),
    panel.grid.minor = element_line(size = 0.5, color = 'white')
  ) +
  lims(x = c(xmin, xmax), y = c(ymin, ymax))
guard_plot3
```

#Bigs plots
adj o/d
fg% ftr
orb% drb%
```{r}
player_ids1 <- get_espn_players('UMass') %>% rename(player = displayName)
player_ids2 <- get_espn_players(Team) %>% rename(player = displayName)
player_ids <- rbind(player_ids1, player_ids2)
Big <- Big %>%
  left_join(player_ids, by = 'player') %>%
  separate(player, into = c('first_name', 'last_name'), sep = ' ')

xmin <- min(Big$adj_oe) - 2.5
xmax <- max(Big$adj_oe) + 2.5
ymin <- min(Big$adj_de) - 2.5
ymax <- max(Big$adj_de) + 2.5

big_plot1 <- Big %>%
  ggplot(aes(adj_oe, adj_de)) +
  geom_mean_lines(aes(x0 = adj_oe, y0 = adj_de), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('Adjusted Efficiencies | Bigs'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'Offense',
       y = 'Defense') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold'),
    panel.grid.major = element_line(size = 1, color = 'white'),
    panel.grid.minor = element_line(size = 0.5, color = 'white')
  ) +
  lims(x = c(xmin, xmax), y = c(ymin, ymax))
big_plot1

Big <- Big %>%
  mutate(
    fg_pct = (fg_pct * 100),
    ft_rate = ((fta/fga) * 100)
  )
xmin <- min(Big$ft_rate) - 2.5
xmax <- max(Big$ft_rate) + 2.5
ymin <- min(Big$fg_pct) - 1.5
ymax <- max(Big$fg_pct) + 1.5

big_plot2 <- Big %>%
  ggplot(aes(ft_rate, fg_pct)) +
  geom_mean_lines(aes(x0 = ft_rate, y0 = fg_pct), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('FTr vs. FG% | Bigs'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'FT Att. Rate',
       y = 'FG%') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold'),
    panel.grid.major = element_line(size = 1, color = 'white'),
    panel.grid.minor = element_line(size = 0.5, color = 'white')
  ) +
  lims(x = c(xmin, xmax), y = c(ymin, ymax))
big_plot2

xmin <- min(Big$oreb_rate) - 1
xmax <- max(Big$oreb_rate) + 1
ymin <- min(Big$dreb_rate) - 1
ymax <- max(Big$dreb_rate) + 1

big_plot3 <- Big %>%
  ggplot(aes(oreb_rate, dreb_rate)) +
  geom_mean_lines(aes(x0 = oreb_rate, y0 = dreb_rate), color = 'black') +
  geom_cbb_headshots(aes(player_id = id.y, width = 0.1)) +
  geom_text(aes(label = last_name), vjust = 4, hjust = 0.5, size = 3.5, fontface = 'bold') +
  theme_minimal() +
  labs(title = glue('ORB% vs. DRB% | Bigs'),
       subtitle = glue('Team(s): UMass vs. {Team}'),
       x = 'ORB%',
       y = 'DRB%') +
  theme(
    plot.title = element_text(face = 'bold', size = 18, hjust = 0.5),
    plot.subtitle = element_text(face = 'bold', size = 12, hjust = 0.5),
    plot.background = element_rect(fill = 'gray89'),
    axis.title = element_text(face = 'bold'),
    panel.grid.major = element_line(size = 1, color = 'white'),
    panel.grid.minor = element_line(size = 0.5, color = 'white')
  ) +
  lims(x = c(xmin, xmax), y = c(ymin, ymax))
big_plot3
```

#save plots
```{r}
ggsave(plot = guard_plot1, filename = savename1)
ggsave(plot = guard_plot2, filename = savename2)
ggsave(plot = guard_plot3, filename = savename3)
ggsave(plot = big_plot1, filename = savename4)
ggsave(plot = big_plot2, filename = savename5)
ggsave(plot = big_plot3, filename = savename6)
```

