---
title: "PostGame_Report"
author: "Greg"
date: "2023-05-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#packages
```{r}
library(hoopR)
library(bigballR)
library(ncaahoopR)
library(gt)
library(cowplot)
library(ggpubr)
library(gtExtras)
library(sportsdataverse)
knitr::opts_knit$set(root.dir = '/Users/gregorylederer/Desktop/Umass Basketball')
```

#inputs
```{r}
year <- '2023'
game_id <-'401514221' #espn
ncaa_game_id <- '5472625' #stats.ncaa.org | play by play
teamH <- 'Richmond' #dict$ESPN
teamA <- 'UMass' #dict$ESPN
ncaa_teamH <- 'Richmond' #dict$NCAA
ncaa_teamA <- 'Massachusetts' #dict$NCAA
full_player_stats <- read.csv('/Users/gregorylederer/Desktop/Umass Basketball/Code/CSVs/22-23 Complete PBP Stats.csv')
total_data <- read.csv('/Users/gregorylederer/Desktop/Umass Basketball/Code/CSVs/22-23 Total Team Game Data.csv')
```

#ORtg and DRtg
```{r}
schedule_H <- get_team_schedule(team.name = ncaa_teamH, season = "2022-23")
stats_H <- get_team_stats(play_by_play_data = get_play_by_play(schedule_H$Game_ID[!is.na(schedule_H$Game_ID)]))

new_stats_H <- data.frame()
for (i in 1:nrow(stats_H)) {
  if (stats_H[i, 'Team'] == ncaa_teamH) {
    new_stats_H <- rbind(new_stats_H, stats_H[i, ])
  }
}
home_off <- round(mean(new_stats_H$ORTG),1)
home_def <- round(mean(new_stats_H$DRTG),1)

schedule_A <- get_team_schedule(team.name = ncaa_teamA, season = "2022-23")
stats_A <- get_team_stats(play_by_play_data = get_play_by_play(schedule_A$Game_ID[!is.na(schedule_A$Game_ID)]))

new_stats_A <- data.frame()
for (i in 1:nrow(stats_A)) {
  if (stats_A[i, 'Team'] == ncaa_teamA) {
    new_stats_A <- rbind(new_stats_A, stats_A[i, ])
  }
}
away_off <- round(mean(new_stats_A$ORTG),1)
away_def <- round(mean(new_stats_A$DRTG),1)

url3 <- paste0('https://www.sports-reference.com/cbb/seasons/men/', year, '-advanced-school-stats.html')
webpage3 <- read_html(url3)
all_team_advanced <- webpage3 %>%
  html_table()
all_team_advanced <- data.frame(all_team_advanced)

all_team_advanced <- subset(all_team_advanced, select = -c(Var.1, Var.9, Var.12, Var.15, Var.18, Var.21))
colnames(all_team_advanced) <- all_team_advanced[1,]
all_team_advanced <- all_team_advanced[-1,]
colnames(all_team_advanced)[8] = 'Conf_W'
colnames(all_team_advanced)[9] = 'Conf_L'
colnames(all_team_advanced)[10] = 'Home_W'
colnames(all_team_advanced)[11] = 'Home_L'
colnames(all_team_advanced)[12] = 'Away_W'
colnames(all_team_advanced)[13] = 'Away_L'
colnames(all_team_advanced)[14] = 'Tm_Pts'
colnames(all_team_advanced)[15] = 'Opp_Pts'
all_team_advanced <- all_team_advanced[-22,]
all_team_advanced <- all_team_advanced[-21,]
all_team_advanced <- all_team_advanced[-42,]
all_team_advanced <- all_team_advanced[-41,]
all_team_advanced <- all_team_advanced[-62,]
all_team_advanced <- all_team_advanced[-61,]
all_team_advanced <- all_team_advanced[-82,]
all_team_advanced <- all_team_advanced[-81,]
all_team_advanced <- all_team_advanced[-102,]
all_team_advanced <- all_team_advanced[-101,]
all_team_advanced <- all_team_advanced[-122,]
all_team_advanced <- all_team_advanced[-121,]
all_team_advanced <- all_team_advanced[-142,]
all_team_advanced <- all_team_advanced[-141,]
all_team_advanced <- all_team_advanced[-162,]
all_team_advanced <- all_team_advanced[-161,]
all_team_advanced <- all_team_advanced[-182,]
all_team_advanced <- all_team_advanced[-181,]
all_team_advanced <- all_team_advanced[-202,]
all_team_advanced <- all_team_advanced[-201,]
all_team_advanced <- all_team_advanced[-222,]
all_team_advanced <- all_team_advanced[-221,]
all_team_advanced <- all_team_advanced[-242,]
all_team_advanced <- all_team_advanced[-241,]
all_team_advanced <- all_team_advanced[-262,]
all_team_advanced <- all_team_advanced[-261,]
all_team_advanced <- all_team_advanced[-282,]
all_team_advanced <- all_team_advanced[-281,]
all_team_advanced <- all_team_advanced[-302,]
all_team_advanced <- all_team_advanced[-301,]
all_team_advanced <- all_team_advanced[-322,]
all_team_advanced <- all_team_advanced[-321,]
all_team_advanced <- all_team_advanced[-342,]
all_team_advanced <- all_team_advanced[-341,]
all_team_advanced <- all_team_advanced[-362,]
all_team_advanced <- all_team_advanced[-361,]
avg <- round(mean(as.numeric(all_team_advanced$ORtg)),1)
```

#colors and logo
```{r}
home_color <- data.frame()
for (i in 1:nrow(ncaa_colors)) {
  if (ncaa_colors[i, 'ncaa_name'] == ncaa_teamH) {
    home_color <- rbind(home_color, ncaa_colors[i, ])
  }
}
home_color <- home_color$primary_color

away_color <- data.frame()
for (i in 1:nrow(ncaa_colors)) {
  if (ncaa_colors[i, 'ncaa_name'] == ncaa_teamA) {
    away_color <- rbind(away_color, ncaa_colors[i, ])
  }
}
away_color <- away_color$primary_color

home_team_url <- data.frame()
for (i in 1:nrow(ncaa_colors)) {
  if (ncaa_colors[i, 'ncaa_name'] == ncaa_teamH) {
    home_team_url <- rbind(home_team_url, ncaa_colors[i, ])
  }
}
home_team_url <- home_team_url$logo_url

away_team_url <- data.frame()
for (i in 1:nrow(ncaa_colors)) {
  if (ncaa_colors[i, 'ncaa_name'] == ncaa_teamA) {
    away_team_url <- rbind(away_team_url, ncaa_colors[i, ])
  }
}
away_team_url <- away_team_url$logo_url

url <- c(away_team_url, home_team_url)
```

#stats and roster
```{r}
player_stats <- get_player_stats(get_play_by_play(ncaa_game_id), multi.games = F, simple = F)

home_roster <- get_roster(teamH, season = '2022-23')
home_roster <- home_roster %>%
  mutate(Jersey = number) %>%
  select(Jersey, player_image)
home_roster <- merge(home_roster, get_team_roster(season = '2022-23', team.name = player_stats$Home[1]), by = 'Jersey')

away_roster <- get_roster(teamA, season = '2022-23')
away_roster <- away_roster %>%
  mutate(Jersey = number) %>%
  select(Jersey, player_image)
away_roster <- merge(away_roster, get_team_roster(season = '2022-23', team.name = player_stats$Away[1]), by = 'Jersey')

team_stats <- get_team_stats(play_by_play_data = get_play_by_play(ncaa_game_id), include_transition = T)
```

#team stats
```{r}
total_data <- total_data %>%
  mutate(TP. = round((TPM/TPA),3))
team_stats <- team_stats %>%
  mutate(TP. = round((TPM/TPA),3))

team_stats <- team_stats %>%
  mutate(off_rtg_perc = round(pnorm((ORTG-mean(total_data$ORTG))/sd(total_data$ORTG)),2),
         efg_perc = round(pnorm((eFG.-mean(total_data$eFG.))/sd(total_data$eFG.)),2),
         tov_perc = round(pnorm((TOrate/(oPOSS-mean(total_data$TOrate)))/sd(total_data$TOrate)),2),
         OReb_perc = round(pnorm((ORB.-mean(total_data$ORB.))/sd(total_data$ORB.)),2),
         FTR_perc = round(pnorm((FTrate-mean(total_data$FTrate))/sd(total_data$FTrate)),2),
         layup_perc = round(pnorm((RIMrate-mean(total_data$RIMrate))/sd(total_data$RIMrate)),2),
         jumper_perc = round(pnorm((MIDrate-mean(total_data$MIDrate))/sd(total_data$MIDrate)),2),
         three_pointer_perc = round(pnorm((TPrate-mean(total_data$TPrate))/sd(total_data$TPrate)),2),
         layup_per_perc = round(pnorm((RIM.-mean(total_data$RIM.))/sd(total_data$RIM.)),2),
         jumper_per_perc = round(pnorm((MID.-mean(total_data$MID.))/sd(total_data$MID.)),2),
         three_pointer_per_perc = round(pnorm((TP.-mean(total_data$TP.))/sd(total_data$TP.)),2),
         score = PTS,
         poss = oPOSS,
         off_rtg = round(ORTG,1),
         halfcourt = (1-oTransPCT),
         halfcourt_rtg = round(ORTG_half,1),
         trans = oTransPCT,
         trans_rtg = round(ORTG_trans,1),
         team = Team,
         efg = round(eFG.*100,1),
         tov = round(TO/oPOSS*100,1),
         OReb = round(ORB.*100,1),
         FTR = round(FTrate*100,1),
         layup_tot = paste0(RIMM, "/", RIMA),
         layup_per = round(RIM.*100,1),
         jumper_tot = paste0(FGM-RIMM-TPM, "/", FGA-RIMA-TPA),
         jumper_per = (round((FGM-RIMM-TPM)/(FGA-RIMA-TPA)*100,1)),
         three_pointer_tot = paste0(TPM,"/",TPA),
         three_pointer_per = round(TPM/TPA*100,1),
         layup = round(RIMrate*100,1),
         jumper = round(MIDrate*100,1),
         three_pointer = round(TPrate*100,1),
         team = Team,
         url=url)
```

#divide them
```{r}

```

